rails_challenge_blog/config/routes.rb
Rails.application.routes.draw do
  resources :my_books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "my_books#index"
end

rails_challenge_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails_challenge_blog/app/models/my_book.rb
class MyBook < ApplicationRecord
  validates :title, length: { minimum: 3 }
  validates :author, length: { minimum: 2 }
  validates :rating, numericality: { only_integer: true }
end


#   title: MyString
# author: MyString
# rating: 9.99
# description: MyText

rails_challenge_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

rails_challenge_blog/app/controllers/my_books_controller.rb
class MyBooksController < ApplicationController
  before_action :set_my_book, only: %i[ show edit update destroy ]

  # GET /my_books or /my_books.json
  def index
    @my_books = MyBook.all
  end

  # GET /my_books/1 or /my_books/1.json
  def show
  end

  # GET /my_books/new
  def new
    @my_book = MyBook.new
  end

  # GET /my_books/1/edit
  def edit
  end

  # POST /my_books or /my_books.json
  def create
    @my_book = MyBook.new(my_book_params)

    respond_to do |format|
      if @my_book.save
        format.html { redirect_to @my_book, notice: "My book was successfully created." }
        format.json { render :show, status: :created, location: @my_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_books/1 or /my_books/1.json
  def update
    respond_to do |format|
      if @my_book.update(my_book_params)
        format.html { redirect_to @my_book, notice: "My book was successfully updated." }
        format.json { render :show, status: :ok, location: @my_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_books/1 or /my_books/1.json
  def destroy
    @my_book.destroy!

    respond_to do |format|
      format.html { redirect_to my_books_path, status: :see_other, notice: "My book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_book
      @my_book = MyBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_book_params
      params.require(:my_book).permit(:title, :author, :rating, :description)
    end
end

rails_challenge_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_challenge_blog/app/helpers/my_books_helper.rb
module MyBooksHelper
end

rails_challenge_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Challenge Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_challenge_blog/app/views/my_books/_form.html.erb
<%= form_with(model: my_book) do |form| %>
  <% if my_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(my_book.errors.count, "error") %> prohibited this my_book from being saved:</h2>

      <ul>
        <% my_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails_challenge_blog/app/views/my_books/_my_book.html.erb
<div id="<%= dom_id my_book %>">
  <p>
    <strong>Title:</strong>
    <%= my_book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= my_book.author %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= my_book.rating %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= my_book.description %>
  </p>

</div>

rails_challenge_blog/app/views/my_books/edit.html.erb
<% content_for :title, "Editing my book" %>

<h1>Editing my book</h1>

<%= render "form", my_book: @my_book %>

<br>

<div>
  <%= link_to "Show this my book", @my_book %> |
  <%= link_to "Back to my books", my_books_path %>
</div>

rails_challenge_blog/app/views/my_books/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "My books" %>

<h1>My books</h1>

<div id="my_books">
  <% @my_books.each do |my_book| %>
    <%= render my_book %>
    <p>
      <%= link_to "Show this my book", my_book %>
    </p>
  <% end %>
</div>

<%= link_to "New my book", new_my_book_path %>

rails_challenge_blog/app/views/my_books/new.html.erb
<% content_for :title, "New my book" %>

<h1>New my book</h1>

<%= render "form", my_book: @my_book %>

<br>

<div>
  <%= link_to "Back to my books", my_books_path %>
</div>

rails_challenge_blog/app/views/my_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @my_book %>

<div>
  <%= link_to "Edit this my book", edit_my_book_path(@my_book) %> |
  <%= link_to "Back to my books", my_books_path %>

  <%= button_to "Destroy this my book", @my_book, method: :delete %>
</div>